server:
  port: 8080

spring:
  cloud: 
   gateway: 
    routes:
      - id: compra
        uri: lb://compra
        predicates:
          - Path=/compra/**
      - id: event
        uri: lb://event
        predicates:
          - Path=/event/**
      - id: ticket
        uri: lb://ticket
        predicates:
          - Path=/ticket/**
      - id: user
        uri: lb://user
        predicates:
          - Path=/user/**
springdoc:
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
    urls:
      - name: event
        url: /event/v3/api-docs
      - name: user
        url: /user/v3/api-docs
      - name: ticket
        url: /ticket/v3/api-docs
      - name: compra
        url: /compra/v3/api-docs
